### ISSUE TITLE
Cannot pass a slice of interface to klog.ErrorS()

### ISSUE THREAD

**Issue by jaythamke** [kubernetes-sigs/logtools#19]
In my use-case I want to pass a slice of interface (`[]interface{}{"key1", "value1"}`) to klog.ErrorS() as described in the below snippet.

```go
func logErrorAndExit(err error, msg string, args ...interface{}) {
	defer klog.FlushAndExit(klog.ExitFlushTimeout, 1)
	klog.ErrorS(err, msg, args...)
}
``` 
However, the `logcheck` is returning following error -

```sh
<Golang-code-file-path> Additional arguments to ErrorS should always be Key Value pairs. Please check if there is any key or value missing.
```

IMO as `klog.ErrorS(....)` is a variadic function (not pure variadic though), then `logcheck` should not return above error if slice of interface is passed as a parameter.

No extra command line option has been passed along with `logcheck` command.

Is this check correct?
How can I exclude this check at the moment?

**Comment by pohly** [comment]
logcheck has some "enable" flags, but nothing specifically just for this case.

You can run it through golangci-lint (see https://github.com/kubernetes/kubernetes/blob/baefd08919a306ecfa830cd8648bd0effd2d25f3/hack/verify-golangci-lint.sh#L139-L147 and https://github.com/kubernetes/kubernetes/blob/baefd08919a306ecfa830cd8648bd0effd2d25f3/hack/golangci-strict.yaml#L38-L43), then you can use `//nolint:logcheck` for this particular code line.

**Comment by jaythamke** [comment]
Thanks, I can check that but it will ultimately make me adapt some of my bash scripts as our Go code is still using `golint` (`'golang.org/x/lint/golint'`) and I do not want to make that change now.
I think over the time disabling this check in `logcheck` would be helpful.

**Comment by pohly** [comment]
A PR doing that would be welcome.

**Comment by jaythamke** [comment]
> A PR doing that would be welcome.

Provided PR - https://github.com/kubernetes-sigs/logtools/pull/20.

**Comment by pohly** [comment]
Resolved through https://github.com/kubernetes-sigs/logtools/pull/20 if I'm not mistaken.

/close
