### ISSUE TITLE
Flaky results for logcheck

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/logtools#23]
Running logcheck seemingly spuriously fails. Happens both locally and in CI. An example of running locally:

```bash
$ logcheck -config scripts/test-infra/logcheck.conf ./cmd/... ./pkg/...  ./source/...
$ logcheck -config scripts/test-infra/logcheck.conf ./cmd/... ./pkg/...  ./source/...
$ logcheck -config scripts/test-infra/logcheck.conf ./cmd/... ./pkg/...  ./source/...
$ logcheck -config scripts/test-infra/logcheck.conf ./cmd/... ./pkg/...  ./source/...
/home/marquiz/go/git/node-feature-discovery/pkg/nfd-master/nfd-master.go:349:13: lis.Close undefined (type "net".Listener has no field or method Close)
logcheck: analysis skipped due to errors in package
logcheck: analysis skipped due to errors in package
logcheck: analysis skipped due to errors in package
logcheck: analysis skipped due to errors in package
```

This happens at least in the [node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery) project.

**Comment by pohly** [comment]
Logcheck just uses `golang.org/x/tools/go/analysis`. It doesn't get involved until after parsing is done. This error must be somewhere in that area, not in logcheck itself.

Which Go version is used to build logcheck? Updating to the latest might help.

**Comment by pohly** [comment]
I was able to reproduce the failure locally with Go 1.21rc. But `golang.org/x/tools/go/analysis` isn't part of the Go release and logcheck was using a pretty old version of it. Updating dependencies seems to have fixed this for me.

Before:
```
$ $GOPATH/bin/stress -p 1 /tmp/logcheck -config scripts/test-infra/logcheck.conf ./cmd/... ./pkg/...  ./source/...
...
15s: 12 runs so far, 6 failures (50.00%)
^C
````

After:
```
1m20s: 72 runs so far, 0 failures
```

**Comment by marquiz** [comment]
Thanks for the really quick response on this one. What is the process of requesting a new release to be tagged? 😊

**Comment by pohly** [comment]
Reminding me :smile:... done.
